# settings.yaml
project_name: "ada-mata-bottle-cap"
experiment_name: "production_yolov9t_fp16"

dataset:
  path: "datasets/bottle_cap/data.yaml"
  img_size: 320

train:
  model_type: "yolov9t.pt"  # <--- GANTI KE YOLOv9t
  epochs: 50
  batch_size: 8
  device: "cpu"
  learning_rate: 0.01

inference:
  confidence_threshold: 0.25
  output_dir: "runs/inference"