# settings.yaml
project_name: "ada-mata-bottle-cap"
experiment_name: "cli_training_run" # Folder output kalau pakai CLI

dataset:
  path: "datasets/bottle_cap/data.yaml"
  img_size: 320 # Sesuai hasil riset kita

train:
  model_type: "yolov8n.pt"
  epochs: 50
  batch_size: 8
  device: "cpu"
  learning_rate: 0.01

inference:
  confidence_threshold: 0.25
  output_dir: "runs/inference"