_wandb:
    value:
        cli_version: 0.23.0
        e:
            1nnar8gtqi8zdw9grh9x62x50n5xjaba:
                codePath: g:\My Drive\We Work The Talk\Ada Mata - Machine Learning Engineer\ada_mata_mle\notebooks\01_data_exploration.ipynb
                codePathLocal: 01_data_exploration.ipynb
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "214748364800"
                        used: "109539086336"
                email: wikanpriambudi@gmail.com
                executable: c:\Users\LENOVO\AppData\Local\pypoetry\Cache\virtualenvs\ada-mata-mle-3IEznrPG-py3.11\Scripts\python.exe
                git:
                    commit: ac852b82a92525dbdaa8ffd1bd4cab82c1f0d43e
                    remote: https://github.com/wikan1602/ada-mata-mle-test.git
                host: Wikan
                memory:
                    total: "16890978304"
                os: Windows-10-10.0.26200-SP0
                program: g:\My Drive\We Work The Talk\Ada Mata - Machine Learning Engineer\ada_mata_mle\notebooks\01_data_exploration.ipynb
                python: CPython 3.11.9
                root: g:\My Drive\We Work The Talk\Ada Mata - Machine Learning Engineer\ada_mata_mle\notebooks
                startedAt: "2025-11-22T13:51:40.172711Z"
                writerId: 1nnar8gtqi8zdw9grh9x62x50n5xjaba
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
            "4": 3.11.9
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
